import type { MetadataRoute } from "next";

/**
 * Web app manifest.
 *
 * Turns the site into an installable PWA: "Add to Home Screen" on iOS,
 * "Install app" on Android and desktop Chrome. Once installed it opens in its
 * own window with no browser chrome, which is the whole point — it stops
 * looking like a bookmark and starts looking like an app.
 *
 * Generated by Next rather than a static file so the values stay in one place.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Calorie Dashboard",
    // Home screens truncate at roughly 12 characters.
    short_name: "Calories",
    description:
      "Log meals by description or photo and track calories and macros.",
    start_url: "/dashboard",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#7c3aed",
    categories: ["health", "fitness", "lifestyle"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // "maskable" lets Android crop to its own shape without clipping the
        // artwork; without it the icon gets a white letterbox.
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
