import type { MetadataRoute } from "next";

import {
  BRAND_SHORT_NAME,
  BRAND_TAGLINE,
  BRAND_TITLE,
} from "@/lib/brand";

/**
 * Web app manifest.
 *
 * Turns the site into an installable PWA: "Add to Home Screen" on iOS,
 * "Install app" on Android and desktop Chrome. Once installed it opens in its
 * own window with no browser chrome, which is the whole point — it stops
 * looking like a bookmark and starts looking like an app.
 *
 * Generated by Next rather than a static file so the values stay in one place.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    // The install prompt and splash screen show `name`; the label under the
    // icon shows `short_name`, which launchers truncate at roughly 12
    // characters — hence the name alone there.
    name: BRAND_TITLE,
    short_name: BRAND_SHORT_NAME,
    description: BRAND_TAGLINE,
    start_url: "/dashboard",
    display: "standalone",
    orientation: "portrait",
    // Both near-black: the splash screen and the status bar should be the
    // page the app actually opens on, not a white flash before it.
    background_color: "#0f0f10",
    theme_color: "#0f0f10",
    categories: ["health", "fitness", "lifestyle"],
    icons: [
      {
        // Listed first so anything that can use vector does. The PNGs below
        // remain because iOS ignores SVG icons entirely.
        src: "/icons/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        // "maskable" lets Android crop to its own shape without clipping the
        // artwork; without it the icon gets a white letterbox.
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
